//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDMU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMUSys : DbContext
    {
        public DMUSys()
            : base("name=DMUSys")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Fag> Fags { get; set; }
        public virtual DbSet<Kode> Kodes { get; set; }
        public virtual DbSet<Lektion> Lektions { get; set; }
        public virtual DbSet<Lektionsbesvarelser> Lektionsbesvarelsers { get; set; }
        public virtual DbSet<Lektionsfiler> Lektionsfilers { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
    }
}
