//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lektion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lektion()
        {
            this.Kodes = new HashSet<Kode>();
            this.Lektionsbesvarelsers = new HashSet<Lektionsbesvarelser>();
            this.Lektionsfilers = new HashSet<Lektionsfiler>();
        }
    
        public int Id { get; set; }
        public System.DateTime Lektionafholdelsestid { get; set; }
        public int Lektionnummer { get; set; }
        public string Lektionsbeskrivelse { get; set; }
        public int SemesterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kode> Kodes { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lektionsbesvarelser> Lektionsbesvarelsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lektionsfiler> Lektionsfilers { get; set; }
    }
}
